dataset:
  root: /mnt/hdd/uav_dataset/Anti-UAV-RGBT
  root_mask: /mnt/hdd/uav_dataset/Anti-UAV-RGBT-Masked-SAM2
  num_workers: 32
  batch_size: 64
  image_size:
  - 256
  - 256
  train_sequences: 70
  val_sequences: 20
  test_sequences: 20
trainer:
  epochs: 50
  optimizer: AdamW
  loss_fn: IoULoss
  lr: 0.0001
  gpu_id: 1
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.15
    patience: 10
    cooldown: 5
  early_stop:
    patience: 10
    min_delta: 0.001
    mode: min
  checkpoint:
    save_dir: checkpoints/ThinDyUNet-AdamW-IoULoss
model:
  name: ThinDyUNet
