dataset:
  train_path: ../../dataset/uav_mask_dataset/train/
  val_path: ../../dataset/uav_mask_dataset/val/
  test_path: ../../dataset/uav_mask_dataset/test/
  num_classes: 2
  num_workers: 16
  batch_size: 4
  image_size: [224,224]

trainer:
  epochs: 100
  optimizer: AdamW
  loss_fn: CrossEntropyLoss
  lr: 0.0001
  gpu_id: 0
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.15
    patience: 15
    cooldown: 5
  early_stop:
    patience: 30
    min_delta: 0.001
    mode: min
  checkpoint: 
    val_path: checkpoints/best_train_uav_dconv.pth
    train_path: checkpoints/best_train_uav_dconv.pth
    test_path: checkpoints/best_test_uav_dconv.pth




