dataset:
  root: /mnt/hdd/uav_dataset/Anti-UAV-RGBT
  root_mask: /mnt/hdd/uav_dataset/Anti-UAV-RGBT-Masked-SAM2
  num_workers: 32
  batch_size: 32
  image_size: [240,240]
  train_sequences: 100
  val_sequences: 20
  test_sequences: 20

trainer:
  epochs: 50
  optimizer: AdamW
  loss_fn: BCEWithLogitsLoss
  lr: 0.0001
  gpu_id: 1
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.15
    patience: 10
    cooldown: 5
  early_stop:
    patience: 5
    min_delta: 0.001
    mode: min
  checkpoint: 
    val_path: checkpoints/best-val.pth
    train_path: checkpoints/best-train.pth
    test_path: checkpoints/best-test.pth

model:
  name: DyUNet




