dataset:
  root: /mnt/hdd/uav_dataset/Anti-UAV-RGBT
  root_mask: /mnt/hdd/uav_dataset/Anti-UAV-RGBT-Masked-SAM2
  num_classes: 2 # TODO: remove this variable
  num_workers: 16
  batch_size: 16
  image_size: [224,224]
  train_sequences: 4
  val_sequences: 1
  test_sequences: 1

trainer:
  epochs: 10
  optimizer: AdamW
  loss_fn: BCEWithLogitsLoss
  lr: 0.0001
  gpu_id: 1
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.15
    patience: 15
    cooldown: 5
  early_stop:
    patience: 30
    min_delta: 0.001
    mode: min
  checkpoint: 
    val_path: checkpoints/best-val.pth
    train_path: checkpoints/best-train.pth
    test_path: checkpoints/best-test.pth




